# Add 'deps' label to any change to *.spec.js files within the source dir
frontend_deps:
  - any: ["**/*.config.{js,ts}, **/*.json"]

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
  - any: ["src/**", "!src/docs/*"]

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
  - any: ["src/**/*.{js,jsx,ts,tsx}"]
    # all: ['!src/main.js']

# Add 'backend` label to any change to *.js files as long as the `main.js` hasn't changed
backend:
  - any: ["src/**/*.go"]

# Add the 'AnyChange' label to any changes within the entire repository if the 'dot' option is set to 'false'
new_changes:
  - "**"
  - "**/.*"
  - "**/.*/**"
  - "**/.*/**/.*"
