AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'Create ECR Repository'
Parameters:
  RepoName:
    Type: String
    Description: Name of the ECR respository
    # AllowedPattern: '[a-z][a-z0-9]{2,19}'
    # ConstraintDescription: Must be lower case letters between 3 and 20 characters.
  
  
Resources:
  EcrRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref RepoName



Outputs:
  EcrRepository:
    Description: Name of the ECR Repository
    Value: !Ref EcrRepository
  RepositoryUri:
    Description: The URI for the specified AWS::ECR::Repository resource. For example, 123456789012.dkr.ecr.us-west-2.amazonaws.com/repository.
    Value: !GetAtt EcrRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-RepositoryUri'

