name: Run CI_from_Reusable

on:
    pull_request:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-test:
        uses: Iknite-Space/iknite-reusable-ci-cd/.github/workflows/ci-cliqet-itamba-api.yaml@main
        with:
            make_file: Makefile
            filename: coverage.cobertura.xml
            path: code-coverage-results.md
            version: 1.21
            threshold: 25
        secrets:
            GRPC_CONTRACTS_DEPLOY_KEY: "${{ secrets.GRPC_CONTRACTS_DEPLOY_KEY }}"

    iknite_reusable_workflow_labeler:
        permissions:
            contents: read
            pull-requests: write

        uses: Iknite-Space/iknite-reusable-ci-cd/.github/workflows/label.yml@main
        with:
            config-path: .github/labeler.yml
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}